#!/usr/bin/env python3
"""Generate the games/levels sidebar navigation for the Wargames site.

Scans ``overthewire/<game>/*.md`` and writes ``_data/navigation/wargames.yml``
as a two-level nav tree (game -> its levels) consumed by the zer0-mistakes
theme's ``nav-tree`` include. Every individual challenge page therefore gets a
clickable entry in the left sidebar.

Run after re-syncing content:  python3 scripts/gen-nav.py
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "overthewire"
OUT = ROOT / "_data" / "navigation" / "wargames.yml"

# Curated difficulty-first ordering; any game not listed is appended A→Z.
GAME_ORDER = [
    "bandit", "leviathan", "krypton", "natas", "narnia", "behemoth",
    "utumno", "maze", "vortex", "manpage",
]

_FM = re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL)


def _front_matter(md: Path) -> dict:
    """Minimal front-matter reader (title + permalink only, no YAML dep)."""
    text = md.read_text(encoding="utf-8", errors="replace")
    m = _FM.match(text)
    fm: dict[str, str] = {}
    if not m:
        return fm
    for line in m.group(1).splitlines():
        km = re.match(r"^(title|permalink)\s*:\s*(.+?)\s*$", line)
        if km:
            fm[km.group(1)] = km.group(2).strip().strip("'\"")
    return fm


def _level_key(stem: str) -> tuple[int, str]:
    """Natural sort: numeric suffix first (bandit2 before bandit10)."""
    m = re.search(r"(\d+)$", stem)
    return (int(m.group(1)), stem) if m else (10**9, stem)


def _label(game: str, title: str, stem: str) -> str:
    """`Bandit0` under the `Bandit` group reads better as `Level 0`."""
    m = re.match(rf"^{re.escape(game)}\s*(\d+)$", title, re.IGNORECASE)
    if m:
        return f"Level {int(m.group(1))}"
    m = re.match(rf"^{re.escape(game)}(\d+)$", stem, re.IGNORECASE)
    if m:
        return f"Level {int(m.group(1))}"
    return title or stem


def build() -> str:
    games = sorted(
        (d for d in CONTENT.iterdir() if d.is_dir()),
        key=lambda d: (GAME_ORDER.index(d.name) if d.name in GAME_ORDER
                       else len(GAME_ORDER) + 1, d.name),
    )

    lines = [
        "# GENERATED by scripts/gen-nav.py — do not edit by hand.",
        "# Left-sidebar navigation for the OverTheWire wargames: one collapsible",
        "# group per game, its individual levels as children. Re-run the script",
        "# after syncing content (./scripts/docs-aggregator/aggregate_docs.sh).",
        "",
        "- title: All games",
        "  icon: bi-controller",
        "  url: /docs/wargames/",
        "",
    ]

    for gdir in games:
        game = gdir.name
        index = gdir / "index.md"
        game_url = None
        if index.exists():
            game_url = _front_matter(index).get("permalink", f"/docs/wargames/{game}/")
        else:
            game_url = f"/docs/wargames/{game}/"

        levels = []
        for md in gdir.glob("*.md"):
            if md.name == "index.md":
                continue
            fm = _front_matter(md)
            url = fm.get("permalink", f"/docs/wargames/{game}/{md.stem}/")
            label = _label(game, fm.get("title", ""), md.stem)
            levels.append((_level_key(md.stem), label, url))
        levels.sort(key=lambda x: x[0])

        lines.append(f"- title: {game.capitalize()}")
        lines.append(f"  url: {game_url}")
        if levels:
            lines.append("  children:")
            for _, label, url in levels:
                lines.append(f"    - title: \"{label}\"")
                lines.append(f"      url: {url}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build(), encoding="utf-8")
    n_games = sum(1 for d in CONTENT.iterdir() if d.is_dir())
    n_levels = sum(1 for d in CONTENT.iterdir() if d.is_dir()
                   for f in d.glob("*.md") if f.name != "index.md")
    print(f"Wrote {OUT.relative_to(ROOT)} — {n_games} games, {n_levels} levels")


if __name__ == "__main__":
    main()
